//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientUI.KrabServicesBoardInteraction {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoardDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class BoardDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.CardListDTO[] CardListsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.UserDTO[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.CardListDTO[] CardLists {
            get {
                return this.CardListsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardListsField, value) != true)) {
                    this.CardListsField = value;
                    this.RaisePropertyChanged("CardLists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.UserDTO[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardListDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class CardListDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.BoardDTO BoardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.CardDTO[] CardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.UserDTO CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.BoardDTO Board {
            get {
                return this.BoardField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardField, value) != true)) {
                    this.BoardField = value;
                    this.RaisePropertyChanged("Board");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.CardDTO[] Cards {
            get {
                return this.CardsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardsField, value) != true)) {
                    this.CardsField = value;
                    this.RaisePropertyChanged("Cards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.UserDTO Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.BoardDTO[] BoardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.CardActivityDTO[] CardActivitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.CardDTO[] CardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.CardListDTO[] CreatedCardListsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.LoginDataDTO LoginDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.CommentDTO[] UserCommentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.BoardDTO[] Boards {
            get {
                return this.BoardsField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardsField, value) != true)) {
                    this.BoardsField = value;
                    this.RaisePropertyChanged("Boards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.CardActivityDTO[] CardActivities {
            get {
                return this.CardActivitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CardActivitiesField, value) != true)) {
                    this.CardActivitiesField = value;
                    this.RaisePropertyChanged("CardActivities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.CardDTO[] Cards {
            get {
                return this.CardsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardsField, value) != true)) {
                    this.CardsField = value;
                    this.RaisePropertyChanged("Cards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.CardListDTO[] CreatedCardLists {
            get {
                return this.CreatedCardListsField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedCardListsField, value) != true)) {
                    this.CreatedCardListsField = value;
                    this.RaisePropertyChanged("CreatedCardLists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.LoginDataDTO LoginData {
            get {
                return this.LoginDataField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginDataField, value) != true)) {
                    this.LoginDataField = value;
                    this.RaisePropertyChanged("LoginData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.CommentDTO[] UserComments {
            get {
                return this.UserCommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCommentsField, value) != true)) {
                    this.UserCommentsField = value;
                    this.RaisePropertyChanged("UserComments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class CardDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.CardActivityDTO[] CardActivitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.CardListDTO CardListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.CommentDTO[] CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.LabelColorDTO[] LabelColorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.UserDTO[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.CardActivityDTO[] CardActivities {
            get {
                return this.CardActivitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CardActivitiesField, value) != true)) {
                    this.CardActivitiesField = value;
                    this.RaisePropertyChanged("CardActivities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.CardListDTO CardList {
            get {
                return this.CardListField;
            }
            set {
                if ((object.ReferenceEquals(this.CardListField, value) != true)) {
                    this.CardListField = value;
                    this.RaisePropertyChanged("CardList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.CommentDTO[] Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.LabelColorDTO[] LabelColors {
            get {
                return this.LabelColorsField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelColorsField, value) != true)) {
                    this.LabelColorsField = value;
                    this.RaisePropertyChanged("LabelColors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.UserDTO[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardActivityDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class CardActivityDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.CardDTO CardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardActivityActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.UserDTO UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.CardDTO Card {
            get {
                return this.CardField;
            }
            set {
                if ((object.ReferenceEquals(this.CardField, value) != true)) {
                    this.CardField = value;
                    this.RaisePropertyChanged("Card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardActivityAction {
            get {
                return this.CardActivityActionField;
            }
            set {
                if ((object.ReferenceEquals(this.CardActivityActionField, value) != true)) {
                    this.CardActivityActionField = value;
                    this.RaisePropertyChanged("CardActivityAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.UserDTO User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class CommentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.CardDTO CardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.UserDTO CommentAuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.CardDTO Card {
            get {
                return this.CardField;
            }
            set {
                if ((object.ReferenceEquals(this.CardField, value) != true)) {
                    this.CardField = value;
                    this.RaisePropertyChanged("Card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.UserDTO CommentAuthor {
            get {
                return this.CommentAuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentAuthorField, value) != true)) {
                    this.CommentAuthorField = value;
                    this.RaisePropertyChanged("CommentAuthor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommentContent {
            get {
                return this.CommentContentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentContentField, value) != true)) {
                    this.CommentContentField = value;
                    this.RaisePropertyChanged("CommentContent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LabelColorDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class LabelColorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.CardDTO[] CardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.CardDTO[] Cards {
            get {
                return this.CardsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardsField, value) != true)) {
                    this.CardsField = value;
                    this.RaisePropertyChanged("Cards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginDataDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class LoginDataDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardInteraction.UserDTO UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardInteraction.UserDTO User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KrabServicesBoardInteraction.IBoardInteractionService", CallbackContract=typeof(ClientUI.KrabServicesBoardInteraction.IBoardInteractionServiceCallback))]
    public interface IBoardInteractionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/AddUserToBoard", ReplyAction="http://tempuri.org/IBoardInteractionService/AddUserToBoardResponse")]
        void AddUserToBoard(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/AddUserToBoard", ReplyAction="http://tempuri.org/IBoardInteractionService/AddUserToBoardResponse")]
        System.Threading.Tasks.Task AddUserToBoardAsync(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RemoveUserFromBoard", ReplyAction="http://tempuri.org/IBoardInteractionService/RemoveUserFromBoardResponse")]
        void RemoveUserFromBoard(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RemoveUserFromBoard", ReplyAction="http://tempuri.org/IBoardInteractionService/RemoveUserFromBoardResponse")]
        System.Threading.Tasks.Task RemoveUserFromBoardAsync(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/AddCardListToBoard", ReplyAction="http://tempuri.org/IBoardInteractionService/AddCardListToBoardResponse")]
        void AddCardListToBoard(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.CardListDTO cardList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/AddCardListToBoard", ReplyAction="http://tempuri.org/IBoardInteractionService/AddCardListToBoardResponse")]
        System.Threading.Tasks.Task AddCardListToBoardAsync(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.CardListDTO cardList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RemoveCardListFromBoard", ReplyAction="http://tempuri.org/IBoardInteractionService/RemoveCardListFromBoardResponse")]
        void RemoveCardListFromBoard(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.CardListDTO cardList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RemoveCardListFromBoard", ReplyAction="http://tempuri.org/IBoardInteractionService/RemoveCardListFromBoardResponse")]
        System.Threading.Tasks.Task RemoveCardListFromBoardAsync(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.CardListDTO cardList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RenameBoard", ReplyAction="http://tempuri.org/IBoardInteractionService/RenameBoardResponse")]
        void RenameBoard(ClientUI.KrabServicesBoardInteraction.BoardDTO board, string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RenameBoard", ReplyAction="http://tempuri.org/IBoardInteractionService/RenameBoardResponse")]
        System.Threading.Tasks.Task RenameBoardAsync(ClientUI.KrabServicesBoardInteraction.BoardDTO board, string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/AddCardToCardListAsync", ReplyAction="http://tempuri.org/IBoardInteractionService/AddCardToCardListAsyncResponse")]
        void AddCardToCardListAsync(ClientUI.KrabServicesBoardInteraction.CardListDTO cardList, ClientUI.KrabServicesBoardInteraction.CardDTO card);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/AddCardToCardListAsync", ReplyAction="http://tempuri.org/IBoardInteractionService/AddCardToCardListAsyncResponse")]
        System.Threading.Tasks.Task AddCardToCardListAsyncAsync(ClientUI.KrabServicesBoardInteraction.CardListDTO cardList, ClientUI.KrabServicesBoardInteraction.CardDTO card);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RemoveCardFromCardListAsync", ReplyAction="http://tempuri.org/IBoardInteractionService/RemoveCardFromCardListAsyncResponse")]
        void RemoveCardFromCardListAsync(ClientUI.KrabServicesBoardInteraction.CardListDTO cardList, ClientUI.KrabServicesBoardInteraction.CardDTO card);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RemoveCardFromCardListAsync", ReplyAction="http://tempuri.org/IBoardInteractionService/RemoveCardFromCardListAsyncResponse")]
        System.Threading.Tasks.Task RemoveCardFromCardListAsyncAsync(ClientUI.KrabServicesBoardInteraction.CardListDTO cardList, ClientUI.KrabServicesBoardInteraction.CardDTO card);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RenameCardList", ReplyAction="http://tempuri.org/IBoardInteractionService/RenameCardListResponse")]
        void RenameCardList(ClientUI.KrabServicesBoardInteraction.CardListDTO cardList, string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RenameCardList", ReplyAction="http://tempuri.org/IBoardInteractionService/RenameCardListResponse")]
        System.Threading.Tasks.Task RenameCardListAsync(ClientUI.KrabServicesBoardInteraction.CardListDTO cardList, string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/AddUserToCard", ReplyAction="http://tempuri.org/IBoardInteractionService/AddUserToCardResponse")]
        void AddUserToCard(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/AddUserToCard", ReplyAction="http://tempuri.org/IBoardInteractionService/AddUserToCardResponse")]
        System.Threading.Tasks.Task AddUserToCardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RemoveUserFromCard", ReplyAction="http://tempuri.org/IBoardInteractionService/RemoveUserFromCardResponse")]
        void RemoveUserFromCard(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RemoveUserFromCard", ReplyAction="http://tempuri.org/IBoardInteractionService/RemoveUserFromCardResponse")]
        System.Threading.Tasks.Task RemoveUserFromCardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/AddLabelColorToCard", ReplyAction="http://tempuri.org/IBoardInteractionService/AddLabelColorToCardResponse")]
        void AddLabelColorToCard(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.LabelColorDTO labelColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/AddLabelColorToCard", ReplyAction="http://tempuri.org/IBoardInteractionService/AddLabelColorToCardResponse")]
        System.Threading.Tasks.Task AddLabelColorToCardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.LabelColorDTO labelColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RemoveLabelColorFromCard", ReplyAction="http://tempuri.org/IBoardInteractionService/RemoveLabelColorFromCardResponse")]
        void RemoveLabelColorFromCard(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.LabelColorDTO labelColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RemoveLabelColorFromCard", ReplyAction="http://tempuri.org/IBoardInteractionService/RemoveLabelColorFromCardResponse")]
        System.Threading.Tasks.Task RemoveLabelColorFromCardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.LabelColorDTO labelColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/AddCommentToCard", ReplyAction="http://tempuri.org/IBoardInteractionService/AddCommentToCardResponse")]
        void AddCommentToCard(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.CommentDTO comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/AddCommentToCard", ReplyAction="http://tempuri.org/IBoardInteractionService/AddCommentToCardResponse")]
        System.Threading.Tasks.Task AddCommentToCardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.CommentDTO comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RemoveCommentFromCard", ReplyAction="http://tempuri.org/IBoardInteractionService/RemoveCommentFromCardResponse")]
        void RemoveCommentFromCard(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.CommentDTO comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RemoveCommentFromCard", ReplyAction="http://tempuri.org/IBoardInteractionService/RemoveCommentFromCardResponse")]
        System.Threading.Tasks.Task RemoveCommentFromCardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.CommentDTO comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/ChangeDueDateOfACard", ReplyAction="http://tempuri.org/IBoardInteractionService/ChangeDueDateOfACardResponse")]
        void ChangeDueDateOfACard(ClientUI.KrabServicesBoardInteraction.CardDTO card, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/ChangeDueDateOfACard", ReplyAction="http://tempuri.org/IBoardInteractionService/ChangeDueDateOfACardResponse")]
        System.Threading.Tasks.Task ChangeDueDateOfACardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/ChangeNameOfACard", ReplyAction="http://tempuri.org/IBoardInteractionService/ChangeNameOfACardResponse")]
        void ChangeNameOfACard(ClientUI.KrabServicesBoardInteraction.CardDTO card, string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/ChangeNameOfACard", ReplyAction="http://tempuri.org/IBoardInteractionService/ChangeNameOfACardResponse")]
        System.Threading.Tasks.Task ChangeNameOfACardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, string newName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBoardInteractionServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/RefreshBoards", ReplyAction="http://tempuri.org/IBoardInteractionService/RefreshBoardsResponse")]
        void RefreshBoards(ClientUI.KrabServicesBoardInteraction.BoardDTO[] boards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/InformAboutLogin", ReplyAction="http://tempuri.org/IBoardInteractionService/InformAboutLoginResponse")]
        void InformAboutLogin(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardInteractionService/InformAboutRegistration", ReplyAction="http://tempuri.org/IBoardInteractionService/InformAboutRegistrationResponse")]
        void InformAboutRegistration(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBoardInteractionServiceChannel : ClientUI.KrabServicesBoardInteraction.IBoardInteractionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BoardInteractionServiceClient : System.ServiceModel.DuplexClientBase<ClientUI.KrabServicesBoardInteraction.IBoardInteractionService>, ClientUI.KrabServicesBoardInteraction.IBoardInteractionService {
        
        public BoardInteractionServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public BoardInteractionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public BoardInteractionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BoardInteractionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BoardInteractionServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void AddUserToBoard(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.UserDTO user) {
            base.Channel.AddUserToBoard(board, user);
        }
        
        public System.Threading.Tasks.Task AddUserToBoardAsync(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.UserDTO user) {
            return base.Channel.AddUserToBoardAsync(board, user);
        }
        
        public void RemoveUserFromBoard(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.UserDTO user) {
            base.Channel.RemoveUserFromBoard(board, user);
        }
        
        public System.Threading.Tasks.Task RemoveUserFromBoardAsync(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.UserDTO user) {
            return base.Channel.RemoveUserFromBoardAsync(board, user);
        }
        
        public void AddCardListToBoard(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.CardListDTO cardList) {
            base.Channel.AddCardListToBoard(board, cardList);
        }
        
        public System.Threading.Tasks.Task AddCardListToBoardAsync(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.CardListDTO cardList) {
            return base.Channel.AddCardListToBoardAsync(board, cardList);
        }
        
        public void RemoveCardListFromBoard(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.CardListDTO cardList) {
            base.Channel.RemoveCardListFromBoard(board, cardList);
        }
        
        public System.Threading.Tasks.Task RemoveCardListFromBoardAsync(ClientUI.KrabServicesBoardInteraction.BoardDTO board, ClientUI.KrabServicesBoardInteraction.CardListDTO cardList) {
            return base.Channel.RemoveCardListFromBoardAsync(board, cardList);
        }
        
        public void RenameBoard(ClientUI.KrabServicesBoardInteraction.BoardDTO board, string newName) {
            base.Channel.RenameBoard(board, newName);
        }
        
        public System.Threading.Tasks.Task RenameBoardAsync(ClientUI.KrabServicesBoardInteraction.BoardDTO board, string newName) {
            return base.Channel.RenameBoardAsync(board, newName);
        }
        
        public void AddCardToCardListAsync(ClientUI.KrabServicesBoardInteraction.CardListDTO cardList, ClientUI.KrabServicesBoardInteraction.CardDTO card) {
            base.Channel.AddCardToCardListAsync(cardList, card);
        }
        
        public System.Threading.Tasks.Task AddCardToCardListAsyncAsync(ClientUI.KrabServicesBoardInteraction.CardListDTO cardList, ClientUI.KrabServicesBoardInteraction.CardDTO card) {
            return base.Channel.AddCardToCardListAsyncAsync(cardList, card);
        }
        
        public void RemoveCardFromCardListAsync(ClientUI.KrabServicesBoardInteraction.CardListDTO cardList, ClientUI.KrabServicesBoardInteraction.CardDTO card) {
            base.Channel.RemoveCardFromCardListAsync(cardList, card);
        }
        
        public System.Threading.Tasks.Task RemoveCardFromCardListAsyncAsync(ClientUI.KrabServicesBoardInteraction.CardListDTO cardList, ClientUI.KrabServicesBoardInteraction.CardDTO card) {
            return base.Channel.RemoveCardFromCardListAsyncAsync(cardList, card);
        }
        
        public void RenameCardList(ClientUI.KrabServicesBoardInteraction.CardListDTO cardList, string newName) {
            base.Channel.RenameCardList(cardList, newName);
        }
        
        public System.Threading.Tasks.Task RenameCardListAsync(ClientUI.KrabServicesBoardInteraction.CardListDTO cardList, string newName) {
            return base.Channel.RenameCardListAsync(cardList, newName);
        }
        
        public void AddUserToCard(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.UserDTO user) {
            base.Channel.AddUserToCard(card, user);
        }
        
        public System.Threading.Tasks.Task AddUserToCardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.UserDTO user) {
            return base.Channel.AddUserToCardAsync(card, user);
        }
        
        public void RemoveUserFromCard(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.UserDTO user) {
            base.Channel.RemoveUserFromCard(card, user);
        }
        
        public System.Threading.Tasks.Task RemoveUserFromCardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.UserDTO user) {
            return base.Channel.RemoveUserFromCardAsync(card, user);
        }
        
        public void AddLabelColorToCard(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.LabelColorDTO labelColor) {
            base.Channel.AddLabelColorToCard(card, labelColor);
        }
        
        public System.Threading.Tasks.Task AddLabelColorToCardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.LabelColorDTO labelColor) {
            return base.Channel.AddLabelColorToCardAsync(card, labelColor);
        }
        
        public void RemoveLabelColorFromCard(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.LabelColorDTO labelColor) {
            base.Channel.RemoveLabelColorFromCard(card, labelColor);
        }
        
        public System.Threading.Tasks.Task RemoveLabelColorFromCardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.LabelColorDTO labelColor) {
            return base.Channel.RemoveLabelColorFromCardAsync(card, labelColor);
        }
        
        public void AddCommentToCard(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.CommentDTO comment) {
            base.Channel.AddCommentToCard(card, comment);
        }
        
        public System.Threading.Tasks.Task AddCommentToCardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.CommentDTO comment) {
            return base.Channel.AddCommentToCardAsync(card, comment);
        }
        
        public void RemoveCommentFromCard(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.CommentDTO comment) {
            base.Channel.RemoveCommentFromCard(card, comment);
        }
        
        public System.Threading.Tasks.Task RemoveCommentFromCardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, ClientUI.KrabServicesBoardInteraction.CommentDTO comment) {
            return base.Channel.RemoveCommentFromCardAsync(card, comment);
        }
        
        public void ChangeDueDateOfACard(ClientUI.KrabServicesBoardInteraction.CardDTO card, System.DateTime date) {
            base.Channel.ChangeDueDateOfACard(card, date);
        }
        
        public System.Threading.Tasks.Task ChangeDueDateOfACardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, System.DateTime date) {
            return base.Channel.ChangeDueDateOfACardAsync(card, date);
        }
        
        public void ChangeNameOfACard(ClientUI.KrabServicesBoardInteraction.CardDTO card, string newName) {
            base.Channel.ChangeNameOfACard(card, newName);
        }
        
        public System.Threading.Tasks.Task ChangeNameOfACardAsync(ClientUI.KrabServicesBoardInteraction.CardDTO card, string newName) {
            return base.Channel.ChangeNameOfACardAsync(card, newName);
        }
    }
}
