//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientUI.KrabServicesBoardManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BoardDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class BoardDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.CardListDTO[] CardListsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.UserDTO[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.CardListDTO[] CardLists {
            get {
                return this.CardListsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardListsField, value) != true)) {
                    this.CardListsField = value;
                    this.RaisePropertyChanged("CardLists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.UserDTO[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardListDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class CardListDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.BoardDTO BoardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.CardDTO[] CardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.UserDTO CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.BoardDTO Board {
            get {
                return this.BoardField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardField, value) != true)) {
                    this.BoardField = value;
                    this.RaisePropertyChanged("Board");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.CardDTO[] Cards {
            get {
                return this.CardsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardsField, value) != true)) {
                    this.CardsField = value;
                    this.RaisePropertyChanged("Cards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.UserDTO Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.BoardDTO[] BoardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.CardActivityDTO[] CardActivitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.CardDTO[] CardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.CardListDTO[] CreatedCardListsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.LoginDataDTO LoginDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.CommentDTO[] UserCommentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.BoardDTO[] Boards {
            get {
                return this.BoardsField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardsField, value) != true)) {
                    this.BoardsField = value;
                    this.RaisePropertyChanged("Boards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.CardActivityDTO[] CardActivities {
            get {
                return this.CardActivitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CardActivitiesField, value) != true)) {
                    this.CardActivitiesField = value;
                    this.RaisePropertyChanged("CardActivities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.CardDTO[] Cards {
            get {
                return this.CardsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardsField, value) != true)) {
                    this.CardsField = value;
                    this.RaisePropertyChanged("Cards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.CardListDTO[] CreatedCardLists {
            get {
                return this.CreatedCardListsField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedCardListsField, value) != true)) {
                    this.CreatedCardListsField = value;
                    this.RaisePropertyChanged("CreatedCardLists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.LoginDataDTO LoginData {
            get {
                return this.LoginDataField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginDataField, value) != true)) {
                    this.LoginDataField = value;
                    this.RaisePropertyChanged("LoginData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.CommentDTO[] UserComments {
            get {
                return this.UserCommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCommentsField, value) != true)) {
                    this.UserCommentsField = value;
                    this.RaisePropertyChanged("UserComments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class CardDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.CardActivityDTO[] CardActivitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.CardListDTO CardListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.CommentDTO[] CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.LabelColorDTO[] LabelColorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.UserDTO[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.CardActivityDTO[] CardActivities {
            get {
                return this.CardActivitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CardActivitiesField, value) != true)) {
                    this.CardActivitiesField = value;
                    this.RaisePropertyChanged("CardActivities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.CardListDTO CardList {
            get {
                return this.CardListField;
            }
            set {
                if ((object.ReferenceEquals(this.CardListField, value) != true)) {
                    this.CardListField = value;
                    this.RaisePropertyChanged("CardList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.CommentDTO[] Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.LabelColorDTO[] LabelColors {
            get {
                return this.LabelColorsField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelColorsField, value) != true)) {
                    this.LabelColorsField = value;
                    this.RaisePropertyChanged("LabelColors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.UserDTO[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardActivityDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class CardActivityDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.CardDTO CardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardActivityActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.UserDTO UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.CardDTO Card {
            get {
                return this.CardField;
            }
            set {
                if ((object.ReferenceEquals(this.CardField, value) != true)) {
                    this.CardField = value;
                    this.RaisePropertyChanged("Card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardActivityAction {
            get {
                return this.CardActivityActionField;
            }
            set {
                if ((object.ReferenceEquals(this.CardActivityActionField, value) != true)) {
                    this.CardActivityActionField = value;
                    this.RaisePropertyChanged("CardActivityAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.UserDTO User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class CommentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.CardDTO CardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.UserDTO CommentAuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.CardDTO Card {
            get {
                return this.CardField;
            }
            set {
                if ((object.ReferenceEquals(this.CardField, value) != true)) {
                    this.CardField = value;
                    this.RaisePropertyChanged("Card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.UserDTO CommentAuthor {
            get {
                return this.CommentAuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentAuthorField, value) != true)) {
                    this.CommentAuthorField = value;
                    this.RaisePropertyChanged("CommentAuthor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommentContent {
            get {
                return this.CommentContentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentContentField, value) != true)) {
                    this.CommentContentField = value;
                    this.RaisePropertyChanged("CommentContent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LabelColorDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class LabelColorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.CardDTO[] CardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.CardDTO[] Cards {
            get {
                return this.CardsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardsField, value) != true)) {
                    this.CardsField = value;
                    this.RaisePropertyChanged("Cards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginDataDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceInteraction.DTO")]
    [System.SerializableAttribute()]
    public partial class LoginDataDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientUI.KrabServicesBoardManager.UserDTO UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientUI.KrabServicesBoardManager.UserDTO User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KrabServicesBoardManager.IBoardManagerService", CallbackContract=typeof(ClientUI.KrabServicesBoardManager.IBoardManagerServiceCallback))]
    public interface IBoardManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardManagerService/GetBoards", ReplyAction="http://tempuri.org/IBoardManagerService/GetBoardsResponse")]
        ClientUI.KrabServicesBoardManager.BoardDTO[] GetBoards();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardManagerService/GetBoards", ReplyAction="http://tempuri.org/IBoardManagerService/GetBoardsResponse")]
        System.Threading.Tasks.Task<ClientUI.KrabServicesBoardManager.BoardDTO[]> GetBoardsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardManagerService/UpdateBoard", ReplyAction="http://tempuri.org/IBoardManagerService/UpdateBoardResponse")]
        ClientUI.KrabServicesBoardManager.BoardDTO UpdateBoard(ClientUI.KrabServicesBoardManager.BoardDTO oldBoard, ClientUI.KrabServicesBoardManager.BoardDTO newBoard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardManagerService/UpdateBoard", ReplyAction="http://tempuri.org/IBoardManagerService/UpdateBoardResponse")]
        System.Threading.Tasks.Task<ClientUI.KrabServicesBoardManager.BoardDTO> UpdateBoardAsync(ClientUI.KrabServicesBoardManager.BoardDTO oldBoard, ClientUI.KrabServicesBoardManager.BoardDTO newBoard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardManagerService/AddBoard", ReplyAction="http://tempuri.org/IBoardManagerService/AddBoardResponse")]
        void AddBoard(ClientUI.KrabServicesBoardManager.BoardDTO board);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardManagerService/AddBoard", ReplyAction="http://tempuri.org/IBoardManagerService/AddBoardResponse")]
        System.Threading.Tasks.Task AddBoardAsync(ClientUI.KrabServicesBoardManager.BoardDTO board);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardManagerService/RemoveBoard", ReplyAction="http://tempuri.org/IBoardManagerService/RemoveBoardResponse")]
        void RemoveBoard(ClientUI.KrabServicesBoardManager.BoardDTO board);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardManagerService/RemoveBoard", ReplyAction="http://tempuri.org/IBoardManagerService/RemoveBoardResponse")]
        System.Threading.Tasks.Task RemoveBoardAsync(ClientUI.KrabServicesBoardManager.BoardDTO board);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBoardManagerServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardManagerService/RefreshBoards", ReplyAction="http://tempuri.org/IBoardManagerService/RefreshBoardsResponse")]
        void RefreshBoards(ClientUI.KrabServicesBoardManager.BoardDTO[] boards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardManagerService/InformAboutRegistration", ReplyAction="http://tempuri.org/IBoardManagerService/InformAboutRegistrationResponse")]
        void InformAboutRegistration(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBoardManagerServiceChannel : ClientUI.KrabServicesBoardManager.IBoardManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BoardManagerServiceClient : System.ServiceModel.DuplexClientBase<ClientUI.KrabServicesBoardManager.IBoardManagerService>, ClientUI.KrabServicesBoardManager.IBoardManagerService {
        
        public BoardManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public BoardManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public BoardManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BoardManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BoardManagerServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public ClientUI.KrabServicesBoardManager.BoardDTO[] GetBoards() {
            return base.Channel.GetBoards();
        }
        
        public System.Threading.Tasks.Task<ClientUI.KrabServicesBoardManager.BoardDTO[]> GetBoardsAsync() {
            return base.Channel.GetBoardsAsync();
        }
        
        public ClientUI.KrabServicesBoardManager.BoardDTO UpdateBoard(ClientUI.KrabServicesBoardManager.BoardDTO oldBoard, ClientUI.KrabServicesBoardManager.BoardDTO newBoard) {
            return base.Channel.UpdateBoard(oldBoard, newBoard);
        }
        
        public System.Threading.Tasks.Task<ClientUI.KrabServicesBoardManager.BoardDTO> UpdateBoardAsync(ClientUI.KrabServicesBoardManager.BoardDTO oldBoard, ClientUI.KrabServicesBoardManager.BoardDTO newBoard) {
            return base.Channel.UpdateBoardAsync(oldBoard, newBoard);
        }
        
        public void AddBoard(ClientUI.KrabServicesBoardManager.BoardDTO board) {
            base.Channel.AddBoard(board);
        }
        
        public System.Threading.Tasks.Task AddBoardAsync(ClientUI.KrabServicesBoardManager.BoardDTO board) {
            return base.Channel.AddBoardAsync(board);
        }
        
        public void RemoveBoard(ClientUI.KrabServicesBoardManager.BoardDTO board) {
            base.Channel.RemoveBoard(board);
        }
        
        public System.Threading.Tasks.Task RemoveBoardAsync(ClientUI.KrabServicesBoardManager.BoardDTO board) {
            return base.Channel.RemoveBoardAsync(board);
        }
    }
}
